---
title: "Relatório Fauna"
author: "Pedro"
date: "2023-01-05"
output: html_document
---

```{r setup, include=FALSE}
library(dunn.test)
setwd("/home/uff/Área de Trabalho/arquivos/lorena/dados_fauna")

df <- read.csv("dados_fauna.txt", h=T, sep="\t")
df<-df[,c(1,3,4,21,22,23,24,25)]
head(df)


```

## Shapiro Test (dados não paramétricos)
```{r cars, echo=FALSE}
for (col in 4:ncol(df)) {
  print(paste(names(df)[col]))
  print(shapiro.test(df[,col]))
}
```



## Kruskall test
```{r, fig.width=15, fig.height=6, echo=FALSE}
for (col in 4:ncol(df)) {
  boxplot(df[,col] ~ df[,"Áreas"] * df[,"Prof"] * df[,"Coleta"], main=paste(names(df)[col]), las=2, xlab="")
  print(paste(names(df)[col]))
    if(kruskal.test(df[,col]~df[,"Áreas"])$p.value < 0.05) {
      dunn.test(df[,col],df["Áreas"])
    }
    
    print(kruskal.test(df[,col]~df[,"Prof"]))
    if(kruskal.test(df[,col]~df[,"Prof"])$p.value < 0.05) {
      dunn.test(df[,col],df["Prof"])
    }
    
    print(kruskal.test(df[,col]~df[,"Coleta"]))
    if(kruskal.test(df[,col]~df[,"Coleta"])$p.value < 0.05) {
      dunn.test(df[,col],df["Coleta"])
    }
  #print(wilcox.test(df[,col]~df[,"Prof"]))
  print(wilcox.test(df[,col]~df[,"Coleta"]))
  }
```

